#!/usr/bin/env python3
"""Interactive bootstrap wizard for new ProjectState repos.

This is an MVP front-end that asks the minimum strategic questions, then runs
`scripts/init_template.py new` with the chosen profile. It stays stdlib-only and
does not mark investigation complete; generated repos still start in bootstrap
mode with `system_investigated: false` and `repo_investigated: false`.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INIT_SCRIPT = ROOT / "scripts" / "init_template.py"
VALID_PROFILES = {"minimal", "solo", "team", "regulated"}


def ask_interactive() -> dict[str, str]:
    print("ProjectState Bootstrap Wizard")
    print("Answer a few strategic questions to scaffold an honest baseline.")
    print()

    project_name = input("Project name: ").strip()
    if not project_name:
        raise SystemExit("Project name is required.")

    repo_role = input("Repo role [downstream_project]: ").strip() or "downstream_project"
    if repo_role not in {"downstream_project", "template_repository"}:
        raise SystemExit(f"Unsupported repo role: {repo_role}")

    profile = input("Profile [solo] (minimal/solo/team/regulated): ").strip() or "solo"
    if profile not in VALID_PROFILES:
        raise SystemExit(f"Unknown profile: {profile}")

    first_milestone = input("First milestone / backlog slice: ").strip()
    if not first_milestone:
        first_milestone = "Establish a truthful baseline"

    runtime_required = input("Will this project have a runtime/users need proof? [no]: ").strip().lower()
    runtime_required_bool = runtime_required in {"yes", "y", "true"}

    evidence_strictness = input("Evidence strictness [standard] (minimal/standard/strict): ").strip() or "standard"
    if evidence_strictness not in {"minimal", "standard", "strict"}:
        raise SystemExit(f"Unknown evidence strictness: {evidence_strictness}")

    return {
        "project_name": project_name,
        "repo_role": repo_role,
        "profile": profile,
        "first_milestone": first_milestone,
        "runtime_required": str(runtime_required_bool).lower(),
        "evidence_strictness": evidence_strictness,
    }


def load_answers(path: Path) -> dict[str, str]:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise SystemExit(f"Could not read answers file: {exc}")
    if not isinstance(data, dict):
        raise SystemExit("Answers file must contain a JSON object")
    return data


def validate_answers(answers: dict[str, str]) -> None:
    required = {"project_name", "profile"}
    missing = required - set(answers.keys())
    if missing:
        raise SystemExit(f"Missing required answers: {sorted(missing)}")
    if answers.get("profile") not in VALID_PROFILES:
        raise SystemExit(f"Unknown profile: {answers.get('profile')}")


def print_plan(answers: dict[str, str], target: Path) -> None:
    print("Bootstrap plan")
    print(f"  Target: {target}")
    print(f"  Project name: {answers['project_name']}")
    print(f"  Repo role: {answers.get('repo_role', 'downstream_project')}")
    print(f"  Profile: {answers['profile']}")
    print(f"  First milestone: {answers.get('first_milestone', 'not specified')}")
    print(f"  Runtime required: {answers.get('runtime_required', 'false')}")
    print(f"  Evidence strictness: {answers.get('evidence_strictness', 'standard')}")
    print()
    print("Generated files will be created by scripts/init_template.py new.")
    print("Investigation fields remain false; the repo starts in bootstrap mode.")


def run_init(answers: dict[str, str], target: Path) -> int:
    args = [
        sys.executable,
        str(INIT_SCRIPT),
        "new",
        "--name",
        answers["project_name"],
        "--target",
        str(target),
        "--profile",
        answers["profile"],
    ]
    completed = subprocess.run(
        args,
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    if completed.stdout:
        print(completed.stdout)
    if completed.stderr:
        print(completed.stderr, file=sys.stderr)
    return completed.returncode


def write_bootstrap_notes(target: Path, answers: dict[str, str]) -> None:
    notes_path = target / "docs" / "bootstrap_wizard_notes.md"
    notes_path.parent.mkdir(parents=True, exist_ok=True)
    notes_path.write_text(
        f"""# Bootstrap Wizard Notes

Generated by `scripts/projectstate_bootstrap_wizard.py`.

- Project name: {answers['project_name']}
- Repo role: {answers.get('repo_role', 'downstream_project')}
- Profile: {answers['profile']}
- First milestone: {answers.get('first_milestone', 'not specified')}
- Runtime required: {answers.get('runtime_required', 'false')}
- Evidence strictness: {answers.get('evidence_strictness', 'standard')}

These answers are a starting point only. The repo remains in bootstrap mode until
the real runtime, deployment, and project truth are investigated and recorded.
""",
        encoding="utf-8",
    )


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Interactive ProjectState bootstrap wizard")
    parser.add_argument("--target", default=".", help="Directory to initialize")
    parser.add_argument("--answers", help="Path to a JSON file with wizard answers")
    parser.add_argument("--dry-run", action="store_true", help="Print plan without writing files")
    return parser.parse_args(argv[1:])


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv or sys.argv)
    target = Path(args.target).resolve()

    if args.answers:
        answers = load_answers(Path(args.answers).resolve())
    else:
        answers = ask_interactive()

    validate_answers(answers)
    print_plan(answers, target)

    if args.dry_run:
        print("\nDry run complete. No files written.")
        return 0

    exit_code = run_init(answers, target)
    if exit_code != 0:
        return exit_code

    write_bootstrap_notes(target, answers)
    print(f"\nBootstrap notes written to {target / 'docs' / 'bootstrap_wizard_notes.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
